PACKAGENAME="Axis C6110 Audio Extensions"
APPTYPE="aarch64"
APPNAME="audio_control"
APPID=""
LICENSENAME="Available"
LICENSEPAGE="none"
VENDOR="MRDN Labs"
REQEMBDEVVERSION="3.0"
APPMAJORVERSION="1"
APPMINORVERSION="8"
APPMICROVERSION="0"
APPGRP="sdk"
APPUSR="sdk"
APPOPTS=""
OTHERFILES=""
SETTINGSPAGEFILE="index.html"
SETTINGSPAGETEXT=""
VENDORHOMEPAGELINK=''
PREUPGRADESCRIPT=""
POSTINSTALLSCRIPT=""
STARTMODE="respawn"
HTTPCGIPATHS=""
