EnableSpeakerGuard="yes" type="bool"
EnableAudioForward="yes" type="bool"
RemoteIP="192.168.1.219" type="string"
RemoteUser="root" type="string"
RemotePass="" type="string"
LocalUser="root" type="string"
LocalPass="pass" type="string"
ActiveMode="instructor" type="string"
