EnableSpeakerGuard="yes" type="bool"
EnableAudioForward="yes" type="bool"
EnableDualAudio="no" type="bool"
RemoteIP="" type="string"
RemoteUser="" type="string"
RemotePass="" type="string"
ActiveMode="instructor" type="string"
HeadphoneNodeName="AudioDevice0Output0" type="string"
SpeakerNodeName="AudioDevice0Output1" type="string"
CaptureNodeName="AudioDevice0Outputs" type="string"
