PACKAGENAME="Audio Monitor"
APPTYPE="aarch64"
APPNAME="audio_monitor"
APPID=""
LICENSENAME="Available"
LICENSEPAGE="none"
VENDOR="Custom"
REQEMBDEVVERSION="2.0"
APPMAJORVERSION="1"
APPMINORVERSION="0"
APPMICROVERSION="0"
APPGRP="sdk"
APPUSR="sdk"
APPOPTS=""
OTHERFILES=""
SETTINGSPAGEFILE=""
SETTINGSPAGETEXT=""
VENDORHOMEPAGELINK=''
PREUPGRADESCRIPT=""
POSTINSTALLSCRIPT=""
STARTMODE="respawn"
HTTPCGIPATHS=""
